from typing import Dict

from ...utils.sector import Sector
from .base import XTrackersBaseScraper


class XTrackersItScraper(XTrackersBaseScraper):
    """
    Scraper for XTrackers ETFs in Italy.
    It fetches listings and holdings data from the XTrackers API (CSV-based).
    """

    LISTINGS_URL = "https://etf.dws.com/api/fundfinder/it-it/datatable"
    HOLDINGS_URL_TEMPLATE = (
        "https://etf.dws.com/etfdata/export/ITA/ITA/csv/product/constituent/{isin}/"
    )
    # TODO: check for sensitive data
    COOKIE = "audiences_it-it=%7B%22a%22%3A%5B%227864d84e-9892-4df4-9d1b-0109d415b8ae%22%5D%2C%22i%22%3Afalse%2C%22e%22%3A%2218%2F09%2F2027%2017%3A30%22%7D"

    COUNTRIES_LANGUAGE = "it"
    SECTORS_MAP: Dict[str, Sector | None] = {
        # GICS sectors
        "SERVIZI DI COMUNICAZIONE": Sector.COMMUNICATION_SERVICES,
        "COMUNICAZIONI": Sector.COMMUNICATION_SERVICES,
        "TELECOMUNICAZIONI": Sector.COMMUNICATION_SERVICES,
        "BENI VOLUTTUARI": Sector.CONSUMER_DISCRETIONARY,
        "BENI DI PRIMA NECESSITÀ": Sector.CONSUMER_STAPLES,
        "BENI DI CONSUMO NON DISCREZIONALI": Sector.CONSUMER_STAPLES,
        "ENERGIA": Sector.ENERGY,
        "FINANZA": Sector.FINANCIALS,
        "FINANZIARIO": Sector.FINANCIALS,
        "SANITÀ": Sector.HEALTH_CARE,
        "ASSISTENZA SANITARIA": Sector.HEALTH_CARE,
        "PRODOTTI INDUSTRIALI": Sector.INDUSTRIALS,
        "INDUSTRIA": Sector.INDUSTRIALS,
        "INDUSTRIALE": Sector.INDUSTRIALS,
        "TECNOLOGIA DELL'INFORMAZIONE": Sector.INFORMATION_TECHNOLOGY,
        "TECNOLOGIA": Sector.INFORMATION_TECHNOLOGY,
        "MATERIALI": Sector.MATERIALS,
        "MATERIE PRIME": Sector.MATERIALS,
        "CHIMICA E MATERIE PRIME": Sector.MATERIALS,
        "IMMOBILIARE": Sector.REAL_ESTATE,
        "SERVIZI DI PUBBLICA UTILITÀ": Sector.UTILITIES,
        "UTENZE": Sector.UTILITIES,
        "GOVERNO": Sector.GOVERNMENT,
        # GICS sub-industries, used by some funds
        "APPARECCHIATURE E STRUMENTI ELETTRONICI": Sector.INFORMATION_TECHNOLOGY,
        "SERVIZI DI CONSULENZA IT E ALTRI SERVIZI CORRELATI": Sector.INFORMATION_TECHNOLOGY,
        "SOFTWARE DI SISTEMA": Sector.INFORMATION_TECHNOLOGY,
        "COMPONENTI E APPARECCHIATURE ELETTRICHE": Sector.INDUSTRIALS,
        "MACCHINE PER L'EDILIZIA E AUTOCARRI PESANTI": Sector.INDUSTRIALS,
        "SERVIZI DI MANUTENZIONE E AMBIENTALI": Sector.INDUSTRIALS,
        "VETTORI ALTERNATIVI": Sector.INDUSTRIALS,
        "TRASMISSIONI VIA CAVO E VIA SATELLITE": Sector.COMMUNICATION_SERVICES,
        "BEVANDE ANALCOLICHE": Sector.CONSUMER_STAPLES,
        "BIRRIFICI": Sector.CONSUMER_STAPLES,
        "CARNI E PRODOTTI ALIMENTARI CONFEZIONATI": Sector.CONSUMER_STAPLES,
        "DISTILLERIE E CASE VINICOLE": Sector.CONSUMER_STAPLES,
        "DISTRIBUTORI DI PRODOTTI ALIMENTARI": Sector.CONSUMER_STAPLES,
        "IPERMERCATI E CENTRI COMMERCIALI": Sector.CONSUMER_STAPLES,
        "PRODOTTI AGRICOLI": Sector.CONSUMER_STAPLES,
        "PRODOTTI PER LA CURA DELLA CASA": Sector.CONSUMER_STAPLES,
        "PRODOTTI PER LA CURA DELLA PERSONA": Sector.CONSUMER_STAPLES,
        "TABACCO": Sector.CONSUMER_STAPLES,
        "VENDITA AL DETTAGLIO DI GENERI ALIMENTARI": Sector.CONSUMER_STAPLES,
        # Not a sector
        "SCONOSCIUTA": None,
    }
